# Generated by Django 4.2.30 on 2026-08-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-vote_count', '-created_at', '-id']},
        ),
    ]
