# Generated by Django 4.2.30 on 2026-08-26 00:00

from django.db import migrations, models
import django.db.models.deletion


def assign_existing_questions_to_default_board(apps, schema_editor):
    Board = apps.get_model('board', 'Board')
    Question = apps.get_model('board', 'Question')

    if not Question.objects.exists():
        return

    default_board = Board.objects.create(
        title='Imported Board',
        code='imported1',
        status='active',
    )
    Question.objects.filter(board__isnull=True).update(board=default_board)


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_question_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(editable=False, max_length=16, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='board.board'),
        ),
        migrations.RunPython(assign_existing_questions_to_default_board, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='question',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='board.board'),
        ),
    ]