# Generated by Django 4.2.30 on 2026-08-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_board_owner'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['status', '-created_at', '-id'], name='board_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['owner', '-created_at', '-id'], name='board_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['board', 'state', '-vote_count', '-created_at', '-id'], name='question_board_rank_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voter_token', 'question'], name='vote_token_question_idx'),
        ),
    ]
